apiVersion: v1
kind: Service
metadata:
  name: eks-app-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: eks-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
