name: CI-CD to EKS
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "495417556969"
  ECR_REPOSITORY: devops-nginx-app
  EKS_CLUSTER_NAME: devops-eks-cluster

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.vars.outputs.image_tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: echo "image_tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::495417556969:role/GitHubActionsEKSRole
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Image
        run: |
          ECR_URL="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
          docker build -t ${ECR_REPOSITORY}:${{ steps.vars.outputs.image_tag }} ./app
          docker tag ${ECR_REPOSITORY}:${{ steps.vars.outputs.image_tag }} \
          ${ECR_URL}/${ECR_REPOSITORY}:${{ steps.vars.outputs.image_tag }}
          docker push ${ECR_URL}/${ECR_REPOSITORY}:${{ steps.vars.outputs.image_tag }}
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.ECR_REPOSITORY }}:${{ steps.vars.outputs.image_tag }}
          format: table
          exit-code: '1'
          severity: CRITICAL

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::495417556969:role/GitHubActionsEKSRole
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${AWS_REGION} --name ${EKS_CLUSTER_NAME}

      - name: Deploy to Staging
        run: |
          helm upgrade --install eks-app ./helm/eks-app \
            -n staging \
            --set image.tag=${{ needs.build.outputs.image_tag }}

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::495417556969:role/GitHubActionsEKSRole
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${AWS_REGION} --name ${EKS_CLUSTER_NAME}

      - name: Deploy to Production
        run: |
          helm upgrade --install eks-app ./helm/eks-app \
            -n production \
            --set image.tag=${{ needs.build.outputs.image_tag }}
